import shutil
import subprocess
from pathlib import Path

import pytest

# Repo hygiene so the tests work on a fresh clone (AUDIT.md §6 decisions 9 and 10).
ROOT = Path(__file__).resolve().parent.parent
FIXTURE = "tests/fixtures/irene_2011.txt"


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)


@pytest.fixture(autouse=True)
def require_git_repo():
    if shutil.which("git") is None or git("rev-parse", "--is-inside-work-tree").returncode != 0:
        pytest.skip("not inside a git work tree")


def test_no_bytecode_tracked():
    tracked = git("ls-files").stdout.splitlines()
    bytecode = [f for f in tracked if f.endswith(".pyc") or "__pycache__/" in f]
    assert bytecode == [], f"compiled files are tracked: {bytecode}"


def test_irene_fixture_not_ignored():
    result = git("check-ignore", "-q", "--no-index", FIXTURE)
    assert result.returncode == 1, f"{FIXTURE} is git-ignored"


def test_no_data_parquet_tracked():
    # Parquet files are regenerated by `python -m data.parse_hurdat2`, never committed
    tracked = git("ls-files", "data").stdout.splitlines()
    parquet = [f for f in tracked if f.endswith(".parquet")]
    assert parquet == [], f"data files are tracked: {parquet}"
